package com.example.tiktokunreposter.tiktok

import org.json.JSONObject

/**
 * Best-effort token discovery from legal local sources: WebView DOM output or
 * WebView/TikTok cookie header saved by the user. This class does not implement
 * X-Bogus, X-Gnarly, _signature, captcha solving, device registration, or any
 * reverse-engineered anti-bot bypass.
 */
object TikTokWebTokenExtractor {
    fun buildDomExtractionScript(): String = """
        (function() {
          function cookie(name) {
            try {
              var parts = (document.cookie || '').split(';');
              for (var i = 0; i < parts.length; i++) {
                var p = parts[i].trim();
                if (p.indexOf(name + '=') === 0) return decodeURIComponent(p.substring(name.length + 1));
              }
            } catch(e) {}
            return null;
          }
          function find(patterns) {
            try {
              var html = document.documentElement ? document.documentElement.innerHTML : '';
              for (var i = 0; i < patterns.length; i++) {
                var m = html.match(patterns[i]);
                if (m && m[1]) return m[1];
              }
            } catch(e) {}
            return null;
          }
          return JSON.stringify({
            secUid: find([/\\"secUid\\":\\"([^\\"]+)\\"/, /"secUid":"([^"]+)"/]),
            csrfToken: cookie('tt_csrf_token') || cookie('csrf_session_id'),
            msToken: cookie('msToken'),
            verifyFp: cookie('s_v_web_id') || cookie('verifyFp'),
            webId: cookie('ttwid')
          });
        })();
    """.trimIndent()

    fun extractFromCookieHeader(cookieHeader: String?): TokenExtractionResult {
        val cookie = CookieHeaderBuilder().sanitize(cookieHeader)
            ?: return TokenExtractionResult.Unsupported("No readable TikTok cookie header")
        val map = parseCookieMap(cookie)
        val tokens = TikTokWebTokens(
            csrfToken = map["tt_csrf_token"] ?: map["csrf_session_id"],
            msToken = map["msToken"],
            verifyFp = map["s_v_web_id"] ?: map["verifyFp"],
            webId = map["ttwid"],
            signatureSupported = false,
            notes = listOf("Only cookie/DOM tokens are extracted. TikTok Web signatures are not generated by this app.")
        )
        return if (tokens.hasAnyUsableToken) TokenExtractionResult.Supported(tokens) else {
            TokenExtractionResult.Unsupported("No optional web tokens found in cookie header", tokens)
        }
    }

    fun parseDomExtractionResult(rawEvaluateJavascriptResult: String?): TokenExtractionResult {
        val jsonText = normalizeEvaluateJavascriptString(rawEvaluateJavascriptResult)
            ?: return TokenExtractionResult.Unsupported("WebView did not return token JSON")
        return try {
            val obj = JSONObject(jsonText)
            val tokens = TikTokWebTokens(
                csrfToken = obj.optString("csrfToken").takeIf { it.isNotBlank() && it != "null" },
                msToken = obj.optString("msToken").takeIf { it.isNotBlank() && it != "null" },
                verifyFp = obj.optString("verifyFp").takeIf { it.isNotBlank() && it != "null" },
                webId = obj.optString("webId").takeIf { it.isNotBlank() && it != "null" },
                secUid = obj.optString("secUid").takeIf { it.isNotBlank() && it != "null" },
                signatureSupported = false,
                notes = listOf("DOM/cookie extraction only. No anti-bot signing implemented.")
            )
            if (tokens.hasAnyUsableToken || !tokens.secUid.isNullOrBlank()) {
                TokenExtractionResult.Supported(tokens)
            } else {
                TokenExtractionResult.Unsupported("No secUid/token visible on this page", tokens)
            }
        } catch (e: Exception) {
            TokenExtractionResult.Unsupported("Failed to parse WebView token JSON")
        }
    }

    fun unsupportedSignatureReason(): String =
        "TikTok Web may require msToken/verifyFp/_signature/X-Bogus/X-Gnarly on some endpoints. " +
            "This app does not reverse engineer or bypass those protections. If TikTok rejects the request, stop and use manual/foreground WebView mode."

    private fun parseCookieMap(cookie: String): Map<String, String> = cookie.split(';')
        .mapNotNull { part ->
            val trimmed = part.trim()
            val idx = trimmed.indexOf('=')
            if (idx <= 0) null else trimmed.substring(0, idx) to trimmed.substring(idx + 1)
        }
        .toMap()

    private fun normalizeEvaluateJavascriptString(raw: String?): String? {
        if (raw.isNullOrBlank() || raw == "null") return null
        return try {
            // evaluateJavascript returns a JSON-encoded string when JS returns a string.
            JSONObject("{\"v\":$raw}").getString("v")
        } catch (_: Exception) {
            raw.removeSurrounding("\"")
                .replace("\\\"", "\"")
                .replace("\\\\", "\\")
                .takeIf { it.startsWith("{") && it.endsWith("}") }
        }
    }
}
